# Generated by Django 3.2.6 on 2021-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_details',
            name='donation_status',
            field=models.CharField(max_length=100),
        ),
    ]
